### ISSUE TITLE
TODO — routes/home

### ISSUE THREAD

**Issue by nichoth** [ssc-half-light/.github#114]
Update so all the posts are correct & use the correct paths/URLs for images.

__the new `getRelevantPosts` function__
* [x] DB query to get metadata of all relevant posts
* [x] when you get the DB response, decrypt all the posts client-side, and put decrypted posts into app state
* [x] IO goes in the `api.ts` file
* [x] in-memory operations go in the `/src/post.ts` file
